### ISSUE TITLE
How to authenticate to enable pushing of branch

### ISSUE THREAD

**Issue by MarkMc1089** [nhsbsa-data-analytics/coffee-and-coding#8]
I tried to push some work to the repo from work laptop, but hit an authentication problem.

```
$ git push -u origin 2021-12-15-shiny-shiny-little-star
Logon failed, use ctrl+c to cancel basic credential prompt.
remote: No anonymous write access.
fatal: Authentication failed for 'https://github.com/nhsbsa-data-analytics/coffee-and-coding.git/'

```

**Comment by adamivisonnhs** [comment]
Can you try using SSH instead of HTTPS?

I don't use the CLI just GitHub Desktop (99% of the time)... maybe your credentials aren't stored... not logged in maybe?

**Comment by adamivisonnhs** [comment]
![image](https://user-images.githubusercontent.com/66741381/145033603-6b50db54-ade9-4215-b582-ca7aacee70be.png)

**Comment by MarkMc1089** [comment]
I finally got ssh working for my personal work repo (yay!). I just forked this project, so hopefully can do a PR once we have the code for next session finished.
